### ISSUE TITLE
kan-extensions-5.1 doesn't build with GHC-9.0

### ISSUE THREAD

**Issue by phadej** [ekmett/kan-extensions#69]
```
src/Data/Functor/Kan/Ran.hs:108:18: error:
    • Couldn't match type: forall (b1 :: k). (g b -> g b1) -> h b1
                     with: (a0 -> a0) -> h b
      Expected: Ran g h (g b) -> (a0 -> a0) -> h b
        Actual: Ran g h (g b) -> forall (b1 :: k). (g b -> g b1) -> h b1
```

I'll make a sweep on kan-extensions versions soon to see which other versions are affected and make according revisions, so this issue is for heads up purposes.

**Comment by phadej** [comment]
Only 5.1 was affected. Revision done.
